name: C Test with GCC

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      run: sudo apt-get update

    - name: Build and run fft test
      run: |
        gcc -o fft_test tests/test_fft.c -lm -std=c99
        ./fft_test

    - name: Build and run intreface test
      run: |
        gcc -o interface_test tests/test_interface.c -lm -std=c99
        ./interface_test