name: C Test with GCC

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      run: sudo apt-get update

    - name: Build and run tests
      run: |
        gcc -o fft_test src/fft.c tests/test_fft.c -lm -std=c11
        ./fft_test
